### ISSUE TITLE
TwoWire::read_from and TwoWire::write_to millis rollover bug

### ISSUE THREAD

**Issue by delta-G** [arduino/ArduinoCore-renesas#195]
The code in bot TwoWire::read_from and TwoWire::write_to includes these lines:

   ```
    timeout_ms = millis() + timeout_ms;
    while(millis() < timeout_ms && bus_status == WIRE_STATUS_UNSET && err == FSP_SUCCESS) {

    }
```
which is not safe for millis rollover.  In the rare occurrence that read_from or write_to is called within timeout_ms of rollover, the code will immediately timeout.  The AVR code for this is written using subtraction as is preached daily on the forum.  

```
  startMicros = micros();
  while(TWI_MRX == twi_state){
    if((twi_timeout_us > 0ul) && ((micros() - startMicros) > twi_timeout_us)) {
      twi_handleTimeout(twi_do_reset_on_timeout);
      return 0;
    }
  }
```

I propose fixing the code to use subtraction like the AVR code.

**Comment by JM-FRANCE** [comment]
`twi_timeout_us` is a `uint32_t`so it's always positive - you only want to check if it's not null

```
  startMicros = micros();
  while(TWI_MRX == twi_state){
    if((twi_timeout_us != 0ul) && ((micros() - startMicros) > twi_timeout_us)) {
      twi_handleTimeout(twi_do_reset_on_timeout);
      return 0;
    }
  }
```
I guess this is for efficiency reasons, avoid the call to micros() and the subtraction and compare if it's null...

maybe the compiler is smart enough to only check for 0 rather than the sign of an unsigned variable.
